### ISSUE TITLE
succintup fails to install binary

### ISSUE THREAD

**Issue by samtvlabs** [succinctlabs/succinctx#226]
## Description

Following the instructions in the [README.md ](https://github.com/succinctlabs/succinctx#installing), succintx fails to install. 

## Expected Behaviour

succintup ; binary downloaded.

## Actual Behaviour

```
 succinctup 

succinctup: installing succinct (version nightly, tag nightly)
succinctup: Removing existing directory /home/ubuntu/.succinct/bin
succinctup: downloading latest succinct binaries from https://cli.succinct.xyz/repos/succinctlabs/sdk/tarball/nightly...
mktemp: too few X's in template ‘succinct.tar.gz’
```

## Possible Solution

https://unix.stackexchange.com/questions/516281/mktemp-too-few-xs-in-template-if-there-are-two-sets-of-x-in-file-name

**Comment by puma314** [comment]
We removed `succinctup` as this was legacy code.
