### ISSUE TITLE
Bugs when run plonky2x/core/examples case.

### ISSUE THREAD

**Issue by ChengYueJia** [succinctlabs/succinctx#238]
I tried to run the `exmples/evm.rs` as follow:
```bash
cargo build --examples
# build circuit
RUST_LOG=debug ../../target/debug/examples/evm build
# prove and wrap prove
RUST_LOG=debug ../../target/debug/examples/evm prove core/examples/evm.json --wrapper-path /verifier
```

But meet a error as below: 
![image](https://github.com/succinctlabs/succinctx/assets/108982045/12979286-a11f-4ca5-9e04-e28ddf70cc3a)

Seems like there are more steps need to do, would you like to show me?

**Comment by shreyas-londhe** [comment]
I'm not able to generate a build itself, how were you able to generate a build @ChengYueJia ?

![Screenshot 2023-11-29 at 4 51 28 PM](https://github.com/succinctlabs/succinctx/assets/62744899/7afff592-8edf-4565-9c62-359b018383db)

**Comment by ChengYueJia** [comment]
Well, the code has been udpated a lots. I didn't meet this error  in previous version.

Seems like you meet new bug, "lack of wrapper solidity file". Better submit pr and ask the dev team.
