### ISSUE TITLE
Succinctup Does Not Work

### ISSUE THREAD

**Issue by shreyas-londhe** [succinctlabs/succinctx#293]
I am following the SuccinctX readme and have run the curl command. But when I run the `succinctup` command, it gives a 404 error. I check the URL at which the binary is being pulled from, it returns the same 404 error.

URL - https://cli.succinct.xyz/succinctlabs/sdk/main/succinctup/succinctup

**Comment by puma314** [comment]
I updated the readme, since this was legacy documentation for tooling that we no longer have.
