### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by tumberger** [succinctlabs/succinctx#360]
I tried building SP1 from source, it seems like it's currently not possible:

> fatal: repository 'https://github.com/succinctlabs/rust/' not found

See here:

https://github.com/succinctlabs/sp1/blob/54b64b646d18cabef3307bb90167d23470736dc3/cli/src/commands/build_toolchain.rs#L38

**Comment by puma314** [comment]
Hey @tumberger, I copied over the issue to the SP1 repo. I'll respond there.
