### ISSUE TITLE
Implement EVM Storage Proof Verification Circuit

### ISSUE THREAD

**Issue by puma314** [succinctlabs/succinctx#58]
**Goal:**
Implement the verification of Ethereum MPT proofs within `plonky2x` to verify account or storage proofs against a block hash. This allows for interesting access to historical EVM data as well as verifying Ethereum state on other chains in combination with Succinct's Ethereum ZK Light Client.  

**Steps:**
@puma314 has implemented a [draft PR](https://github.com/succinctlabs/sdk/pull/56/files) that provides a template for implementation of MPT proofs (and RLP encoding/decoding specific to the Ethereum MPT). The steps to take this template and implement a circuit based off of it involve the following tasks: 

- Use an [existing open-source implementation](https://github.com/JumpCrypto/plonky2-crypto/blob/main/src/hash/keccak256.rs) of `keccack256` of fixed length and variable length hashing and import it in our repo
- Implement each individual component in the [template](https://github.com/succinctlabs/sdk/pull/56/files#diff-1692e81efb30820507d48a88f568c3b146803a6c0fa1cb7c9b579b540f83d900R16) (such as `is_leq`, `is_eq`, `to_sized_nibbles`, etc.) as a method on our `Bytes32` builder: 
- Implement `verify_decoded_list` to constraint a RLP encoding of an array and it's elements, as a circuit based on templated implementation [here](https://github.com/succinctlabs/sdk/pull/56/files#diff-1692e81efb30820507d48a88f568c3b146803a6c0fa1cb7c9b579b540f83d900R48)
- Full implementation of `MPT_verify` based on template [here](https://github.com/succinctlabs/sdk/pull/56/files#diff-1692e81efb30820507d48a88f568c3b146803a6c0fa1cb7c9b579b540f83d900R123) that combines above ingredients
- Write tests for testing `MPT` verification circuit and test edge cases, including null value, etc.

You will learn a lot about random linear combination tricks to make circuits efficient by doing this issue!

**Estimated Effort:**

Based on the template that was merged by @puma314 here, we estimate that implementing this as a circuit should take around 1 month (medium size project). The circuit implementation will be quite straightforward as it simply takes the current template and converts it to circuit form.

**Contact Information:**

Please reach out on telegram at @pumatheuma if you are interested in working on this issue. Contributors to this issue will be eligible for grants.

**Comment by ameya-deshmukh** [comment]
@jtguibas is this still open to take up?
